BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "fichelocalisation"(
    "DATE_OBSERV" TEXT NOT NULL,
    "OBSERV_NOM" TEXT NOT NULL,
    "FORET_NOM" TEXT NOT NULL,
    "TRIAGE" TEXT NOT NULL,
    "STRATE" TEXT NOT NULL,
    "ALTITUDE" TEXT NOT NULL,
    "ORIENTATION" TEXT NOT NULL,
    "NBESSENCE" TEXT NOT NULL,
    "PARCELLE_NO" TEXT NOT NULL,
    "CANTON" TEXT NOT NULL,
    "PLACETTE_NO" TEXT NOT NULL,
    "PENTE" NUMBER NOT NULL,
    "PROFONDEUR" NUMBER NOT NULL,
    "ROCHE_MERE" NUMBER NOT NULL,
    "AGE_MOY" NUMBER NOT NULL,
    "longitude" NUMBER NOT NULL,
    "latitude" NUMBER NOT NULL,
    "FORET_NOM" NUMBER NOT NULL
);


CREATE TABLE IF NOT EXISTS "fichedescription"(
    "DATE_OBSERV" TEXT NOT NULL,
    "ESSENCE" TEXT NOT NULL,
    "STDEV_CODE" TEXT NOT NULL,
    "COUV_CODE" NUMBER NOT NULL,
    "FRUCTIFICATION" TEXT NOT NULL,
    "REGENERATION" TEXT NOT NULL,
    "SEMI_NB" NUMBER NOT NULL,
    "ETAT_SANITAIRE" NUMBER NOT NULL,
    "BOIS_GIS" NUMBER NOT NULL,
    "ECIMAGE" NUMBER NOT NULL,
    "H_MOY" NUMBER NOT NULL,    
    "C_MOY" NUMBER NOT NULL,
    "SURFACE" NUMBER NOT NULL,
    "BRIN_NB" NUMBER NOT NULL,
    "SOUCHE_NB" NUMBER NOT NULL,
    "FORET_NOM" NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS "fichedendrometrique"(
    "DATE_OBSERV" TEXT NOT NULL,
    "ESSENCE" TEXT NOT NULL,
    "DEMASCLE" TEXT NOT NULL,
    "CODE" NUMBER NOT NULL,
    "CLASSE" TEXT NOT NULL,
    "FORET_NOM" NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS "ficheechantillont" (
    "DATE_OBSERV" TEXT NOT NULL,
    "ESSENCE" TEXT NOT NULL,
    "AECH_ETAGE" TEXT DEFAULT NULL,
    "AECH_C1" NUMBER DEFAULT NULL,
    "AECH_C2" NUMBER DEFAULT NULL,
    "AECH_EP1" NUMBER DEFAULT NULL,
    "AECH_EP2" NUMBER DEFAULT NULL,
    "AECH_LCERNES" NUMBER DEFAULT NULL,
    "AECH_HT" NUMBER DEFAULT NULL,
    "AECH_HF" NUMBER DEFAULT NULL,
    "AECH_HDEM" NUMBER DEFAULT NULL,
    "FORET_NOM" NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS "fihcedominant"(
    "DATE_OBSERV" TEXT NOT NULL,
    "ESSENCE" TEXT NOT NULL,
    "ADOM_C" NUMBER NOT NULL,
    "ADOM_AGE" NUMBER NOT NULL,
    "ADOM_H" NUMBER NOT NULL,
    "FORET_NOM" NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS "foret"(
    "FORET_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "FORET_NOM" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "serie"(
    "FORET_ID" INTEGER NOT NULL,
    "SERIE_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
CONSTRAINT fk_serie
    FOREIGN KEY ("FORET_ID")
    REFERENCES foret("FORET_ID")
);

CREATE TABLE IF NOT EXISTS "groupe"(
    "FORET_ID" INTEGER NOT NULL,
    "SERIE_ID" INTEGER NOT NULL,
    "GROUPE_ID" INTEGER  PRIMARY KEY AUTOINCREMENT,
CONSTRAINT fk_groupe1
    FOREIGN KEY ("FORET_ID")
    REFERENCES foret("FORET_ID"),

CONSTRAINT fk_groupe2
    FOREIGN KEY ("SERIE_ID")
    REFERENCES serie("SERIE_ID")
);

CREATE TABLE IF NOT EXISTS "strate"(
    "FORET_ID" INTEGER NOT NULL,
    "SERIE_ID" INTEGER NOT NULL,
    "GROUPE_ID" INTEGER NOT NULL,
    "STRATE_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
CONSTRAINT fk_strate1
    FOREIGN KEY ("FORET_ID")
    REFERENCES foret("FORET_ID"),

CONSTRAINT fk_strate2
    FOREIGN KEY ("SERIE_ID")
    REFERENCES serie("SERIE_ID"),

CONSTRAINT fk_strate3
    FOREIGN KEY ("GROUPE_ID")
    REFERENCES groupe("GROUPE_ID")
);

CREATE TABLE IF NOT EXISTS "parcelle"(
    "FORET_ID" INTEGER NOT NULL,
    "SERIE_ID" INTEGER NOT NULL,
    "GROUPE_ID" INTEGER NOT NULL,
    "STRATE_ID" INTEGER NOT NULL,
    "PARCELLE_ID" INTEGER PRIMARY KEY AUTOINCREMENT,

CONSTRAINT fk_parcelle1
    FOREIGN KEY ("FORET_ID")
    REFERENCES foret("FORET_ID"),

CONSTRAINT fk_parcelle2
    FOREIGN KEY ("SERIE_ID")
    REFERENCES serie("SERIE_ID"),

CONSTRAINT fk_parcelle3
    FOREIGN KEY ("GROUPE_ID")
    REFERENCES groupe("GROUPE_ID"),

CONSTRAINT fk_parcelle4
    FOREIGN KEY ("STRATE_ID")
    REFERENCES strate("STRATE_ID")

);

CREATE TABLE IF NOT EXISTS "PLACETTE"(
    "FORET_ID" INTEGER NOT NULL,
    "SERIE_ID" INTEGER NOT NULL,
    "GROUPE_ID" INTEGER NOT NULL,
    "STRATE_ID" INTEGER NOT NULL,
    "PARCELLE_ID" INTEGER NOT NULL,
    "PLACETTE_ID" INTEGER AUTOINCREMENT PRIMARY KEY,

CONSTRAINT fk_placette1
    FOREIGN KEY ("FORET_ID")
    REFERENCES foret("FORET_ID"),

CONSTRAINT fk_placette2
    FOREIGN KEY ("SERIE_ID")
    REFERENCES serie("SERIE_ID"),

CONSTRAINT fk_placette3
    FOREIGN KEY ("GROUPE_ID")
    REFERENCES groupe("GROUPE_ID"),

CONSTRAINT fk_placette4
    FOREIGN KEY ("STRATE_ID")
    REFERENCES strate("STRATE_ID"),

CONSTRAINT fk_placette5
    FOREIGN KEY ("PARCELLE_ID")
    REFERENCES parcelle("PARCELLE_ID")

);

COMMIT;


    /*SELECT * FROM fichelocalisation AS fl
        INNER JOIN fichedescription AS fdesc ON fdesc.DATE_OBSERV= fl.DATE_OBSERV
        INNER JOIN ficheechantillont AS fe on fe.DATE_OBSERV= fl.DATE_OBSERV
        INNER JOIN fihcedominant AS fd on fd.DATE_OBSERV= fl.DATE_OBSERV
        WHERE DATE_OBSERV='20-06-2021'; 2021-06-21 */